name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Push Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build & Push Backend
        run: |
          docker build -t adityakbr/eduapp2026:backend-prod ./server
          docker push adityakbr/eduapp2026:backend-prod

      - name: Build & Push Frontend
        run: |
          docker build -t adityakbr/eduapp2026:frontend-prod ./client
          docker push adityakbr/eduapp2026:frontend-prod

  deploy:
    name: Deploy on EC2
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull latest images
        run: |
          docker pull adityakbr/eduapp2026:backend-prod
          docker pull adityakbr/eduapp2026:frontend-prod

      - name: Restart containers
        run: |
          cd /home/ubuntu/app
          docker compose down
          docker compose up -d

      - name: Cleanup unused images
        run: docker image prune -f
